databases:
  - name: fanTalking_DB
    databaseName: fantalking_db
    user: fanTalking
    region: singapore

services:
  - type: web
    name: fanTalking
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fanTalking_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false



